server:
    port: 3004
management:
  port: 4004
  security:
    enabled: false
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
    instance:
      metadata-map:
         management.port: ${management.port}
spring:
  application:
    name: demo-server
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
  datasource:
      url: jdbc:mysql://localhost:3309/test1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      schema: classpath:/ddl/init.ddl
      initialize: true
      continue-on-error: true
feign:
  hystrix:
    enabled: true