rabbitmq:
  container_name: dev_rabbit
  hostname: rabbit
  image: rabbitmq:3.6.6-management
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER = guest
    - RABBITMQ_DEFAULT_PASS = guest

zipkin_mysql:
    image: mysql:5.6.23
    ports:
      - "3308:3306"
    environment:
       TZ : "Asia/Shanghai"
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: zipkin
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

test1_mysql:
    image: mysql:5.6.23
    ports:
      - "3309:3306"
    environment:
       TZ : "Asia/Shanghai"
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: test1
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

test2_mysql:
    image: mysql:5.6.23
    ports:
      - "3310:3306"
    environment:
       TZ : "Asia/Shanghai"
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: test2
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

zookeeper :
  image: zookeeper:3.4.11
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka
  links:
     - zookeeper:zk
  ports:
    - "9092:9092"
  environment:
    KAFKA_ADVERTOSED_HOST_NAME: localhost
    KAFKA_ADVERTOSED_PORT: "9092"
    KAFKA_ZOOKEEPER_CONNECT: zk:2181

redis:
  image: redis:4.0
  ports:
    - "6379:6379"