server:
    port: 3001
management:
  port: 4001
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
    instance:
      metadata-map:
         management.port: ${management.port}
spring:
  application:
    name: test-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  zipkin:
#    base-url: http://localhost:9411