server:
    port: 3002
management:
  port: 4002
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
    instance:
      metadata-map:
         management.port: ${management.port}
spring:
  application:
    name: test-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9412
